---
- name: Base configs for all servers
  tags: base
  hosts: all
  gather_facts: false
  roles:
  - {role: base}

- name: Common configuration
  tags: common
  hosts: all
  roles:
  - {role: common}

- name: Management configuration
  tags: management
  hosts: management
  roles:
  - {role: management}

- name: DSH Configuration (swift)
  tags: management
  hosts: all:!management
  roles:
  - role: dsh
    dsh_server: "{{prefix}}-management"
    dsh_group: swift

- name: DSH Configuration (proxy)
  tags: management
  hosts: proxy
  roles:
  - role: dsh
    dsh_server: "{{prefix}}-management"
    dsh_group: proxy

- name: DSH Configuration (storage)
  tags: management
  hosts: storage
  roles:
  - role: dsh
    dsh_server: "{{prefix}}-management"
    dsh_group: storage

- name: Storage configuration
  tags: storage
  hosts: storage
  roles:
  - {role: storage}
  - {role: rings, ring_master: "{{prefix}}-management"}
  - {role: object, tags: ['object']}
  - {role: container, tags: ['container']}
  - {role: account, tags: ['account']}

- name: Proxy configuration
  tags: proxy
  hosts: proxy
  roles:
  - {role: proxy}
  - {role: rings, ring_master: "{{prefix}}-management"}

- name: Build rings
  tags: add-rings
  hosts: storage
  roles:
    - {role: generate-rings, ring_master: "{{prefix}}-management", when: swift_generate_rings == true}

- name: Pull rings
  tags: rings
  hosts: storage:proxy
  roles:
    - {role: pull-rings, ring_master: "{{prefix}}-management"}
