---
- name: Install packages
  apt: pkg=swift-account

- name: start account-server
  service: name=swift-account enabled=yes state=started

- name: drop account-server conf
  template: dest=/etc/swift/account-server.conf src=account-server.conf.j2 owner=swift mode=0644
  notify: restart swift-account
