---
- name: Ensure graphite packages
  apt: pkg=statsd-c state=present
  with_items:
    - apache2
    - libapache2-mod_wsgi
    - graphite-carbon
    - graphite-web

- name: drop graphite defaults
  template: dest=/etc/default/graphite-carbon src=graphite-carbon.j2 mode=0644
  notify: restart carbon-cache

- name: drop graphite local_settings.py
  template: dest=/etc/graphite/local_settings.py src=local_settings.py.j2 mode=0644
  notify: restart apache2

- name: drop apache2 graphite config
  template: dest=/etc/apache2/sites-available/graphite src=graphite.j2
  notify: restart apache2

- stat: path=/etc/apache2/sites-enabled/graphite
  register: g

# TODO (wilk): This notify is not working.
- name: a2ensite graphite
  shell: a2ensite graphite
  when: g.stat is defined and not g.stat.exists
  notify: restart apache2

- name: Upgrade graphite database versioning
  shell: graphite-manage syncdb